$software = Get-ChildItem HKLM:\Software\Microsoft\Windows\CurrentVersion\Uninstall | 
select -expand pschildname 

foreach ($entry in $software) 
{
get-itemproperty -path "HKLM:\Software\Microsoft\Windows\CurrentVersion\Uninstall\$entry" | 
select pschildname,displayname,publisher
}


# To view all available properties that can be listed, do 
# get-childitem HKLM:\software\microsoft\windows\currentversion\uninstall
# get-itemproperty -path "{0D94F75A-0EA6-4951-B3AF-B145FA9E05C6}" | get-member
# (replace the GUID with one generated by the get-childitem command)
